package hellocucumber;

import java.util.List;

import cucumber.api.DataTable;
import cucumber.api.java.en.Given;

public class Stepdefs_API {

    //    @Given("^I have the following animals: cow, horse, sheep$")
    // Modify the expression by hand:
    @Given("^I have the following animals: (.*)")
    public void i_have_the_following_animals(List<String> animals) throws Exception {
        System.out.println("The Stepdefs got animals: " + animals);
    }

    // This method signature is auto generated by cucumber
    @Given("^I have the following friends:$")
    public void i_have_the_following_friends(DataTable table) throws Exception {
        // Write code here that turns the phrase above into concrete actions
        // For automatic transformation, change DataTable to one of
        // List<YourType>, List<List<E>>, List<Map<K,V>> or Map<K,V>.
        // E,K,V must be a scalar (String, Integer, Date, enum etc)
        List<String> list = table.asList(String.class);
        System.out.println("The Stepdefs got friends: " + list);
    }
}
